---
# tasks file for nginx
- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default site config
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Add new default site config
  copy:    
    src: /etc/ansible/roles/nginx/files/my_default.conf
    dest: /etc/nginx/sites-available/default    
  notify: reload_nginx